### PR TITLE
remove blue border

### PR DESCRIPTION
**Pull request by AsmaIbrahimButt**
## 🛠️ Fixes Issue
-I fixed the issue #212 .I remove the blue border around the buttons.
-----------------------------------------------------------

### 👨‍💻 Changes Proposed
Before changing to the codebase the buttons have a blue border around it .After adding some css or bootstrap classes I fix that issue.

-----------------------------------------------------------

### :heavy_check_mark: Check List ( Check all the applicable boxes )
- [ ] My code follows the code style of this project.
- [ ] This PR does not contain Plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.
-----------------------------------------------------------

### :memo:  Note to reviewers
- _List users with @ to send Notifications_
-----------------------------------------------------------

### 📷 Screenshots
-----------------------------------------------------------

WhatsApp Image 2022-04-10 at 10 51 16 AM jpeg

### CODE REVIEW

**Comment by AsmaIbrahimButt** [comment]
@rucha0702 Kindly review a pull request.Thanks

**Comment by the-macson** [comment]
In your PR there some are conflicts 
please resolve and inform me

**Comment by AsmaIbrahimButt** [comment]
@the-macson Sure ,Thanks

**Comment by AsmaIbrahimButt** [comment]
its resolved

**Comment by the-macson** [comment]
Good work @AsmaIbrahimButt

**Pull request merged**
