### PR TITLE
update licence in readme file

### LINKED ISSUE #171: Adding licence in readme

### PR DESCRIPTION
**Pull request by ratika-12**
- add licence in readme.md file 
-----------------------------------------------------------

close #171

### CODE REVIEW

**Comment by ratika-12** [comment]
please review this

**Comment by ratika-12** [comment]
@AMAN123956 @the-macson please review this

**Comment by the-macson** [comment]
waiting for @rucha0702 review

**Comment by rucha0702** [comment]
> waiting for @rucha0702 review

seems fine

**Comment by the-macson** [comment]
okay @rucha0702

**Pull request merged**
