### PR TITLE
Git&GitHub

### PR DESCRIPTION
**Pull request by Sabyasachi-Seal**
## 🛠️ Fixes Issue
- [Add Resource for Git](https://github.com/DSC-JSS-NOIDA/QuickLearn/issues/294)
-----------------------------------------------------------

### 👨‍💻 Changes Proposed
- New Course
-----------------------------------------------------------

### :heavy_check_mark: Check List ( Check all the applicable boxes )
- [x] My code follows the code style of this project.
- [x] This PR does not contain Plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
-----------------------------------------------------------

### :memo:  Note to reviewers
- _List users with @ to send Notifications_
-----------------------------------------------------------

### 📷 Screenshots
-----------------------------------------------------------
image

### CODE REVIEW

**Comment by Sabyasachi-Seal** [comment]
Please add the GSSoC tag and also a Level tag so that this PR can be counted for GSSoC. Thanks.
Also, if there are any errors/suggested changes, do tell.

**Comment by rucha0702** [comment]
There are some conflicts in the PR @Sabyasachi-Seal

**Comment by Sabyasachi-Seal** [comment]
> There are some conflicts in the PR @Sabyasachi-Seal 

Yes I saw that, But i cannot change or access them as I am not a moderator for this repo, ig only the owner and collaborators can solve merge conflicts.

**Comment by rucha0702** [comment]
> > There are some conflicts in the PR @Sabyasachi-Seal
> 
> Yes I saw that, But i cannot change or access them as I am not a moderator for this repo, ig only the owner and collaborators can solve merge conflicts.

They can be resolved at your end as well. Conflicts are present in the getResource.js file, probably because the domain names are repeating. Make sure to pull the code before pushing.

**Comment by Sabyasachi-Seal** [comment]
> > > There are some conflicts in the PR @Sabyasachi-Seal
> > 
> > Yes I saw that, But i cannot change or access them as I am not a moderator for this repo, ig only the owner and collaborators can solve merge conflicts.
> 
> They can be resolved at your end as well. Conflicts are present in the getResource.js file, probably because the domain names are repeating. Make sure to pull the code before pushing.

Okay, I will try to fix them and update. Thanks.

**Comment by Sabyasachi-Seal** [comment]
@rucha0702 I have resolved the merge conflits. Please review.

Also could you please add the GSSoC tag and the Level tag?

**Comment by rucha0702** [comment]
@Sabyasachi-Seal merged it but the resources are not displaying. Could you fix that?

**Comment by Sabyasachi-Seal** [comment]
> @Sabyasachi-Seal merged it but the resources are not displaying. Could you fix that?

sure, could you send me a screenshot of that place ?

**Comment by rucha0702** [comment]
Sure, here it is 

image

**Comment by Sabyasachi-Seal** [comment]
> Sure, here it is 
> 
> image
> 

ill get right on it

**Comment by Sabyasachi-Seal** [comment]
Fixed : https://github.com/DSC-JSS-NOIDA/QuickLearn/pull/322

**Comment by rucha0702** [comment]
Great job @Sabyasachi-Seal ! Thank you for contributing :)

**Pull request merged**
