### PR TITLE
Pull Request for Issue#142 Improving the padding of the cards in Features Section and make the features card images rounded to make them look more attractive 

### PR DESCRIPTION
**Pull request by Hritik-Verma41**
Have added the required changes to the code so that the features section cards look more bettter.

### CODE REVIEW

**Comment by AMAN123956** [comment]
@Hritik-Verma41 can u resolve the conflicts that are there

**Comment by Hritik-Verma41** [comment]
@AMAN123956 ok  will work on that

**Comment by Hritik-Verma41** [comment]
@AMAN123956 I have added you to my forked repo contributors please check now

**Comment by Hritik-Verma41** [comment]
@AMAN123956 I've removed the conflicts

**Pull request merged**
