### PR TITLE
adjusted mobile responsiveness of home page

### PR DESCRIPTION
**Pull request by maura-dev**
## 🛠️ Fixes Issue
-Fixes issue #159 
-----------------------------------------------------------

### 👨‍💻 Changes Proposed
- Changed the width and alignment of text on mobile
- Changed button alignment and size on mobile
- Added animation to the home page
- Changed the styling of the input fields
-----------------------------------------------------------

### :heavy_check_mark: Check List ( Check all the applicable boxes )
- [ :heavy_check_mark: ] My code follows the code style of this project.
- [ :heavy_check_mark: ] This PR does not contain Plagiarized content.
- [ :heavy_check_mark: ] The title of my pull request is a short description of the requested changes.
-----------------------------------------------------------

### :memo:  Note to reviewers
- _List users with @ to send Notifications_
-----------------------------------------------------------

### 📷 Screenshots
-----------------------------------------------------------

Annotation 2022-03-17 231538

### CODE REVIEW

**Comment by rucha0702** [comment]
@the-macson Recheck this PR. Have the resources gone missing here? Homepage img is also enlarged which is not needed. Responsiveness seems fine.

**Comment by the-macson** [comment]
@maura-dev  
Can you decrease size of home page image and make PR again on the same issue

**Comment by the-macson** [comment]
@rucha0702 
No resources are not missing here

**Comment by maura-dev** [comment]
@the-macson , i've updated the pr ..... I reduced the image size on moile screen
image

**Comment by rucha0702** [comment]
@the-macson looks good now.

**Comment by the-macson** [comment]
Great work @maura-dev

**Pull request merged**
