### PR TITLE
Layout: contact us page layout is changed

### PR DESCRIPTION
**Pull request by k99sharma**
## 🛠️ Fixes Issue
- Contact Us section layout is changed
-----------------------------------------------------------

### 👨‍💻 Changes Proposed
- Improved design
- Improved layout
- Border radius and shadows
- Changed font size and color
-----------------------------------------------------------

### :heavy_check_mark: Check List ( Check all the applicable boxes )
- [ ✔️ ] My code follows the code style of this project.
- [ ✔️ ] This PR does not contain Plagiarized content.
- [ ✔️ ] The title of my pull request is a short description of the requested changes.
-----------------------------------------------------------

### :memo:  Note to reviewers
- I have made the PR as GSSOC'22 contribution
- Please check if changes are right
-----------------------------------------------------------

### 📷 Screenshots
-----------------------------------------------------------
Change:

Screenshot (25)

Screenshot (27)

Before:
Screenshot (8)

### CODE REVIEW

**Comment by the-macson** [comment]
It was good but it would be better if you can do the same for dark mode and centre the (contact us) heading

**Comment by rucha0702** [comment]
> It was good but it would be better if you can do the same for dark mode and centre the (contact us) heading

Yeah that would be good.

**Comment by k99sharma** [comment]
Sure. I will put the contact us heading in the center and fix the box shadow

**Comment by k99sharma** [comment]
@rucha0702 @the-macson  I have made the changes please check if it's correct. If you want any more changes I will update them.

**Comment by rucha0702** [comment]
Left align this: 
image

**Comment by k99sharma** [comment]
Screenshot (30)

**Comment by the-macson** [comment]
Good work @k99sharma

**Pull request merged**
