### PR TITLE
made changes to UI of contact section

### PR DESCRIPTION
**Pull request by AnweshaRoses**
Made changes to the form and contact info and also made the logos purple

### CODE REVIEW

**Comment by invsto** [comment]
Hey @AnweshaRoses , we saw the UI changes(they are good) but you removed the query and collaboration related information. Maybe retain that content in your changes and then create a PR for merging.

Content:
image

**Comment by rucha0702** [comment]
Hey @AnweshaRoses , we saw the UI changes(they are good), but you removed the query and collaboration related information. Maybe retain that content in your changes and then create a PR.

Info:
image

**Comment by AnweshaRoses** [comment]
Hey I have made the new changed I am a little new to this can you please check and tell me if you can see the collaborating message as well

**Comment by rucha0702** [comment]
Hey! yes the collaboration message is visible : )

**Pull request merged**
